bplm/sfdx-src/main/default/objects/Business_Process__c/Business_Process__c.object-meta.xml
<CustomObject>
    <description>Describe what is your business process</description>
    <label>Business Process</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bplm/sfdx-src/main/default/objects/Business_Process_Stage__c/Business_Process_Stage__c.object-meta.xml
<CustomObject>
    <label>Business Process Stage</label>
    <nameField>
        <label>Business Process Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Process Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bplm/sfdx-src/main/default/objects/Business_Process_Stage__c/fields/Business_Process__c.field-meta.xml
<CustomField>
    <fullName>Business_Process__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Select business process this stage belong to</description>
    <inlineHelpText>Select business process this stage belong to</inlineHelpText>
    <label>Business Process</label>
    <referenceTo>Business_Process__c</referenceTo>
    <relationshipLabel>Business Process Stages</relationshipLabel>
    <relationshipName>Business_Process_Stages</relationshipName>
    <type>Lookup</type>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process_Step__c/Business_Process_Step__c.object-meta.xml
<CustomObject>
    <label>Business Process Step</label>
    <nameField>
        <label>Business Process Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Process Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bplm/sfdx-src/main/default/objects/Business_Process_Step__c/fields/Business_Process_Stage__c.field-meta.xml
<CustomField>
    <fullName>Business_Process_Stage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Process Stage</label>
    <referenceTo>Business_Process_Stage__c</referenceTo>
    <relationshipLabel>Business Process Steps</relationshipLabel>
    <relationshipName>Business_Process_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process_Step_Task_Dependency__c/Business_Process_Step_Task_Dependency__c.object-meta.xml
<CustomObject>
    <label>Business Process Step Task Dependency</label>
    <nameField>
        <displayFormat>BPSTD-{00000000}</displayFormat>
        <label>Business Process Step Task Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Process Step Task Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bplm/sfdx-src/main/default/objects/Business_Process_Step_Task_Dependency__c/fields/Business_Process_Step_Task_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Business_Process_Step_Task_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Process Step Task Mapping</label>
    <referenceTo>Business_Process_Step_Task_Mapping__c</referenceTo>
    <relationshipLabel
  >Business Process Step Task Dependencies</relationshipLabel>
    <relationshipName>Business_Process_Step_Task_Dependencies</relationshipName>
    <type>Lookup</type>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process_Step_Task_Mapping__c/Business_Process_Step_Task_Mapping__c.object-meta.xml
<CustomObject>
    <label>Business Process Step Task Mapping</label>
    <nameField>
        <displayFormat>BPSTM-{00000000}</displayFormat>
        <label>Business Process Step Task Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Process Step Task Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bplm/sfdx-src/main/default/objects/Business_Process_Step_Task_Mapping__c/fields/Business_Process_Step__c.field-meta.xml
<CustomField>
    <fullName>Business_Process_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Process Step</label>
    <referenceTo>Business_Process_Step__c</referenceTo>
    <relationshipLabel>Business Process Step Task Mappings</relationshipLabel>
    <relationshipName>Business_Process_Step_Task_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process_Step_Task_Mapping__c/fields/Business_Process_Task__c.field-meta.xml
<CustomField>
    <fullName>Business_Process_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Process Task</label>
    <referenceTo>Business_Process_Task__c</referenceTo>
    <relationshipLabel>Business Process Step Task Mappings</relationshipLabel>
    <relationshipName>Business_Process_Step_Task_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process_Task__c/Business_Process_Task__c.object-meta.xml
<CustomObject>
    <label>Business Process Task</label>
    <nameField>
        <label>Business Process Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Process Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bplm/sfdx-src/main/default/objects/Business_Process_Workflow_Action__c/Business_Process_Workflow_Action__c.object-meta.xml
<CustomObject>
    <label>Business Process Workflow Action</label>
    <nameField>
        <label>Business Process Workflow Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Process Workflow Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bplm/sfdx-src/main/default/objects/Business_Process_Workflow_Action__c/fields/Business_Process_Workflow_Rule__c.field-meta.xml
<CustomField>
    <fullName>Business_Process_Workflow_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Process Workflow Rule</label>
    <referenceTo>Business_Process_Workflow_Rule__c</referenceTo>
    <relationshipLabel>Business Process Workflow Actions</relationshipLabel>
    <relationshipName>Business_Process_Workflow_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process_Workflow_Rule__c/Business_Process_Workflow_Rule__c.object-meta.xml
<CustomObject>
    <description>Define a workflow rule as a marker interface</description>
    <label>Business Process Workflow Rule</label>
    <nameField>
        <label>Business Process Workflow Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Process Workflow Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bplm/sfdx-src/main/default/objects/Business_Process_Workflow_Rule__c/fields/Business_Process__c.field-meta.xml
<CustomField>
    <fullName>Business_Process__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Process</label>
    <referenceTo>Business_Process__c</referenceTo>
    <relationshipLabel>Business Process Workflow Rules</relationshipLabel>
    <relationshipName>Business_Process_Workflow_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process_Workflow_Rule__c/fields/Business_Process_Step_Task_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Business_Process_Step_Task_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Process Step Task Mapping</label>
    <referenceTo>Business_Process_Step_Task_Mapping__c</referenceTo>
    <relationshipLabel>Business Process Workflow Rules</relationshipLabel>
    <relationshipName>Business_Process_Workflow_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

bplm/sfdx-src/main/default/classes/BPLM_SchemaFactory.cls
/**
 * This {@link BPLM_SchemaFactory} class provide useful factory methods for Schema namespace.
 * @author Rahul Chaudhary (rchaudhary@fiskerinc.com)
 * @version 0.0.1-Alpha
 * @since April 2023
 */
public class BPLM_SchemaFactory {
  // Schema Cache for BPLM
  private static Map<Schema.SObjectType, Map<String, Schema.SObjectField>> bplmSchema = new Map<Schema.SObjectType, Map<String, Schema.SObjectField>>();
  private static List<Schema.SObjectType> bplmObjects = new List<Schema.SObjectType> {
    Business_Process__c.SObjectType,
    Business_Process_Stage__c.SObjectType,
    Business_Process_Step__c.SObjectType,
    Business_Process_Task__c.SObjectType,
    Business_Process_Step_Task_Mapping__c.SObjectType,
    Business_Process_Step_Task_Dependency__c.SObjectType,
    Business_Process_Workflow_Rule__c.SObjectType,
    Business_Process_Workflow_Action__c.SObjectType
  };
  /**
   * <p>
   *  This method generate bplmSchema (SObjectTypes used in BPLM and their respective fields)
   * </p>
   * @return
   */
  private static Map<Schema.SObjectType, Map<String, Schema.SObjectField>> loadBPLMConfigurationSchema() {   
    for (Schema.SObjectType typ : bplmObjects) {
      bplmSchema.put(typ, typ.getDescribe().fields.getMap());
    }
    return bplmSchema;
  }

  /*
  * This method return BPLM schema (SObjectTypes used in BPLM and their respective fields)
  * @param useCache - return cached schema if available else regenerate and return
  */
  public static Map<Schema.SObjectType, Map<String, Schema.SObjectField>> getBPLMConfigurationSchema() {
      return loadBPLMConfigurationSchema();
  }

  private static String generateSchemaSOQL() {
    if(bplmSchema == null || bplmSchema.isEmpty()) {
      loadBPLMConfigurationSchema();
    }
     
    return null;
  }