bplm/sfdx-src/main/default/objects/Business_Process__c/Business_Process__c.object-meta.xml
<CustomObject>
    <description>Describe what is your business process</description>
    <label>Business Process</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bplm/sfdx-src/main/default/objects/Business_Process__c/fields/Business_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Brand_Name__c</fullName>
    <formula>Business_Org__r.Name</formula>
    <label>Business Brand Name</label>
    <type>Text</type>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process__c/fields/Business_Org__c.field-meta.xml
<CustomField>
    <fullName>Business_Org__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Org</label>
    <referenceTo>BusinessBrand</referenceTo>
    <relationshipLabel>Business Processes</relationshipLabel>
    <relationshipName>Business_Processes</relationshipName>
    <type>Lookup</type>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process__c/fields/Business_Process_Owner__c.field-meta.xml
<CustomField>
    <fullName>Business_Process_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>business process owner i.e. dept head?</description>
    <inlineHelpText>business process owner i.e. dept head?</inlineHelpText>
    <label>Business Process Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Business Processes</relationshipLabel>
    <relationshipName>BP2BpOwner</relationshipName>
    <type>Lookup</type>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process__c/fields/Business_SObject_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_SObject_Type__c</fullName>
    <description>Which SObject Type will represent this process records/</description>
    <label>Business SObject Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process__c/fields/Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Developer_Name__c</fullName>
    <formula>SUBSTITUTE(TRIM(Name), &apos; &apos;, &apos;_&apos;)</formula>
    <label>Developer Name</label>
    <type>Text</type>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this business process active</description>
    <inlineHelpText>Is this business process active</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process__c/fields/Process_Summary__c.field-meta.xml
<CustomField>
    <fullName>Process_Summary__c</fullName>
    <label>Process Summary</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Process_Type</valueSetName>
    </valueSet>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process_Stage__c/Business_Process_Stage__c.object-meta.xml
<CustomObject>
    <label>Business Process Stage</label>
    <nameField>
        <label>Business Process Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Process Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bplm/sfdx-src/main/default/objects/Business_Process_Step__c/Business_Process_Step__c.object-meta.xml
<CustomObject>
    <label>Business Process Step</label>
    <nameField>
        <label>Business Process Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Process Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bplm/sfdx-src/main/default/objects/Business_Process_Step__c/fields/Buffer_Days__c.field-meta.xml
<CustomField>
    <fullName>Buffer_Days__c</fullName>
    <label>Buffer Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process_Step__c/fields/Business_Days_To_Complete__c.field-meta.xml
<CustomField>
    <fullName>Business_Days_To_Complete__c</fullName>
    <description>Days required to complete step</description>
    <inlineHelpText>Days required to complete step</inlineHelpText>
    <label>Business Days To Complete</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process_Step__c/fields/Business_Process_Stage__c.field-meta.xml
<CustomField>
    <fullName>Business_Process_Stage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Process Stage</label>
    <referenceTo>Business_Process_Stage__c</referenceTo>
    <relationshipLabel>Business Process Steps</relationshipLabel>
    <relationshipName>Business_Process_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process_Step__c/fields/is_Active__c.field-meta.xml
<CustomField>
    <fullName>is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>is this step active?</description>
    <inlineHelpText>is this step active?</inlineHelpText>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process_Step__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process_Step_Task_Mapping__c/Business_Process_Step_Task_Mapping__c.object-meta.xml
<CustomObject>
    <label>Business Process Step Task Mapping</label>
    <nameField>
        <displayFormat>BPSTM-{00000000}</displayFormat>
        <label>Business Process Step Task Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Process Step Task Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bplm/sfdx-src/main/default/objects/Business_Process_Step_Task_Mapping__c/fields/Business_Process_Step__c.field-meta.xml
<CustomField>
    <fullName>Business_Process_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Process Step</label>
    <referenceTo>Business_Process_Step__c</referenceTo>
    <relationshipLabel>Business Process Step Task Mappings</relationshipLabel>
    <relationshipName>Business_Process_Step_Task_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

bplm/sfdx-src/main/default/objects/Business_Process_Step_Task_Mapping__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

bplm/sfdx-src/main/default/globalValueSets/Business_Process_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Project Management</fullName>
        <isActive>false</isActive>
        <label>Project Management</label>
    </customValue>
    <customValue>
        <fullName>Enhancement</fullName>
        <isActive>false</isActive>
        <label>Enhancement</label>
    </customValue>
    <customValue>
        <fullName>New Initiative</fullName>
        <isActive>false</isActive>
        <label>New Initiative</label>
    </customValue>
    <customValue>
        <fullName>Intake Process</fullName>
        <isActive>false</isActive>
        <label>Intake Process</label>
    </customValue>
    <customValue>
        <fullName>Release Management</fullName>
        <isActive>false</isActive>
        <label>Release Management</label>
    </customValue>
    <masterLabel>Business Process Type</masterLabel>
</GlobalValueSet>

bplm/sfdx-src/main/default/classes/BPLM_SchemaTransformer.cls
public class BPLM_SchemaTransformer {
  // Business Process Fields
  private static Map<String, String> businessProcessFields = new Map<String, String>{
    'Business_Process_Step__r.Business_Process_Stage__r.Business_Process__r.id' => 'processId',
    'Business_Process_Step__r.Business_Process_Stage__r.Business_Process__r.name' => 'processName',
    'Business_Process_Step__r.Business_Process_Stage__r.Business_Process__r.business_process_owner__c' => 'processOwner',
    'Business_Process_Step__r.Business_Process_Stage__r.Business_Process__r.process_summary__c' => 'processSummary',
    'Business_Process_Step__r.Business_Process_Stage__r.Business_Process__r.business_sobject_type__c' => 'businessObject',
    'Business_Process_Step__r.Business_Process_Stage__r.Business_Process__r.is_active__c' => 'isActive',
    'Business_Process_Step__r.Business_Process_Stage__r.Business_Process__r.business_org__c' => 'businessOrg',
    'Business_Process_Step__r.Business_Process_Stage__r.Business_Process__r.business_brand_name__c' => 'businessBrand',
    'Business_Process_Step__r.Business_Process_Stage__r.Business_Process__r.type__c' => 'processType',
    'Business_Process_Step__r.Business_Process_Stage__r.Business_Process__r.developer_name__c' => 'developerName'
  };

  private static List<String> businessProcessStageFields = new List<String>{
    'Business_Process_Step__r.Business_Process_Stage__r.Buffer_Days__c',
    'Business_Process_Step__r.Business_Process_Stage__r.Business_Days_To_Complete__c',
    'Business_Process_Step__r.Business_Process_Stage__r.Business_Process__c',
    'Business_Process_Step__r.Business_Process_Stage__r.Name',
    'Business_Process_Step__r.Business_Process_Stage__r.Business_Process_Stage_Owner__c',
    'Business_Process_Step__r.Business_Process_Stage__r.Days_Before_Due_Date_For_At_Risk__c',
    'Business_Process_Step__r.Business_Process_Stage__r.Is_Active__c',
    'Business_Process_Step__r.Business_Process_Stage__r.Priority__c',
    'Business_Process_Step__r.Business_Process_Stage__r.Sequence__c',
    'Business_Process_Step__r.Business_Process_Stage__r.Stage_Summary__c',
    'Business_Process_Step__r.Business_Process_Stage__r.Id'
  };

  private static BPLM_Model.BPLM_SchemaModel getSchemaModel(
    List<Business_Process_Step_Task_Mapping__c> schema
  ) {
    BPLM_Model.BPLM_SchemaModel model = new BPLM_Model.BPLM_SchemaModel();
    if (schema == null && schema.size() == 0) {
      throw new BPLM_Model.BPLM_ModelException(BPLM_Model.DATA_ERROR);
    }

    // Arrange business process fields
    Business_Process_Step_Task_Mapping__c mapping = schema.get(0);
    model.businessBrand = mapping.Business_Process_Step__r.Business_Process_Stage__r.Business_Process__r.business_brand_name__c;

    model.businessObject = mapping.Business_Process_Step__r.Business_Process_Stage__r.Business_Process__r.business_sobject_type__c;

    model.businessOrg = mapping.Business_Process_Step__r.Business_Process_Stage__r.Business_Process__r.business_org__c;

    model.developerName = mapping.Business_Process_Step__r.Business_Process_Stage__r.Business_Process__r.developer_name__c;

    model.processName = mapping.Business_Process_Step__r.Business_Process_Stage__r.Business_Process__r.name;

    model.processId = mapping.Business_Process_Step__r.Business_Process_Stage__r.Business_Process__r.id;

    model.isActive = mapping.Business_Process_Step__r.Business_Process_Stage__r.Business_Process__r.is_active__c;

    model.processOwner = mapping.Business_Process_Step__r.Business_Process_Stage__r.Business_Process__r.business_process_owner__c;

    model.processSummary = mapping.Business_Process_Step__r.Business_Process_Stage__r.Business_Process__r.process_summary__c;

    model.processType = mapping.Business_Process_Step__r.Business_Process_Stage__r.Business_Process__r.type__c;

    // Arrange stages
    Map<Id, BPLM_Model.BPLM_StageModel> stagesMap = new Map<Id, BPLM_Model.BPLM_StageModel>();
    for (Business_Process_Step_Task_Mapping__c m : schema) {
        if(stagesMap.get(m.Business_Process_Step__r.Business_Process_Stage__r.Id) == null) {
            BPLM_Model.BPLM_StageModel sm = new BPLM_Model.BPLM_StageModel();
            sm.bufferDays = m.Business_Process_Step__r.Business_Process_Stage__r.Buffer_Days__c;
            sm.businessDaysToComplete = m.Business_Process_Step__r.Business_Process_Stage__r.Business_Days_To_Complete__c;
            sm.businessProcess = m.Business_Process_Step__r.Business_Process_Stage__r.Business_Process__c;
            sm.stageName = m.Business_Process_Step__r.Business_Process_Stage__r.Name;
            sm.stageOwner = m.Business_Process_Step__r.Business_Process_Stage__r.Business_Process_Stage_Owner__c;
            sm.daysBeforeDueDateForAtRisk = m.Business_Process_Step__r.Business_Process_Stage__r.Days_Before_Due_Date_For_At_Risk__c;
            sm.isActive = m.Business_Process_Step__r.Business_Process_Stage__r.Is_Active__c;
            sm.priority = m.Business_Process_Step__r.Business_Process_Stage__r.Priority__c;
            sm.sequence = m.Business_Process_Step__r.Business_Process_Stage__r.Sequence__c;
            sm.stageSummary = m.Business_Process_Step__r.Business_Process_Stage__r.Stage_Summary__c;
            sm.stageId = m.Business_Process_Step__r.Business_Process_Stage__r.Id;
            stagesMap.put(m.Business_Process_Step__r.Business_Process_Stage__r.Id, sm);
        }
    }

    if(!stagesMap.isEmpty())
    {
      List<BPLM_Model.BPLM_StageModel> stages = stagesMap.values();
      stages.sort();
      model.stages.addAll(stages);
    }
    return model;
  }

  public static BPLM_Model.BPLM_SchemaModel getBPLMProcessByName(String name) {
    BPLM_SchemaRepository.BPLM_ISchemaRepository repository = new BPLM_SchemaRepository();
    try {
      List<Business_Process_Step_Task_Mapping__c> schema = repository.getBPLMSchemaByProcessName(
        name
      );
      return getSchemaModel(schema);
    } catch (Exception e) {
      throw new BPLM_Model.BPLM_ModelException(e);
    }
  }
}