bplm/sfdx-src/main/default/objects/Business_Process__c/Business_Process__c.object-meta.xml
<CustomObject>
    <description>Describe what is your business process</description>
    <label>Business Process</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bplm/sfdx-src/main/default/objects/BusinessBrand/fields/Business_Brand_Leader__c.field-meta.xml
<CustomField>
    <fullName>Business_Brand_Leader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Brand Leader</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Business Brands</relationshipLabel>
    <relationshipName>Business_Brands</relationshipName>
    <type>Lookup</type>
</CustomField>

bplm/sfdx-src/main/default/classes/BPLM_TestDataFactory.cls
public class BPLM_TestDataFactory {

    public static Contact createContact(Boolean isSave)
    {
        Contact c = new Contact(
            FirstName='Test',
            LastName='Contact'
        );
        if(isSave)
        {
            insert c;
        }
        return c;
    }

    public static BusinessBrand createBusinessBrand(Boolean isSave) {
        BusinessBrand bp = new BusinessBrand(name = 'Digital & Business');
        if(isSave)
        {
            Contact c = createContact(isSave);
            bp.Business_Brand_Leader__c = c.Id;
            insert bp;
        }
        return bp;
    }

    public static Business_Process__c createBusinessProcess() {
        return null;
    }
}